sudo: required

services: 
  - docker

before_install:
  - docker build -t easternlai/cultree-client -f Dockerfile.dev .

script:
  - docker run easternlai/cultree-client npm run test -- --coverage

deploy:
  provider: script
  script bash aws_ecr_push.sh  #script still needs to be created after production build is ready
  on:
    branch: master
